networks:
  default:
    name: 'traefik'

services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    network_mode: host
    command:
      "--configfile /wor/traefik/traefik-wor.yml"
    volumes:
      - ./config:/wor/traefik
      - ./src:/plugins-local/src
      - ./config/.traefik.yml:/plugins-local/src/github.com/dominique57/wor_traefik/.traefik.yml

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    ports:
      - 5000:80
