http:
  routers:
    my-router:
      entryPoints:
        - http
      middlewares:
        - wor
      service: service-whoami
      rule: Path(`/whoami`)

  services:
    service-whoami:
      loadBalancer:
        servers:
          - url: http://localhost:5000
        passHostHeader: false

  middlewares:
    wor:
      plugin:
        dev:
          Foo: Bar
